### ISSUE TITLE
Definir condições operacionais

### ISSUE THREAD

**Issue by AlanPinheir0** [felipelannes/projeto-de-sistemas-oceanicos-1#2]
- [x] Definir tempo de fila em Itaqui

- [x] Verificar prancha do Açu

**Comment by AlanPinheir0** [comment]
- [x] Carga a  ser transportada (Tipo(s) e tonelagem) 
- [x] Portos utilizados e justificativas;
- [x] Eficiência nos portos;  
- [x] Nº de Viagens;

**Comment by felipelannes** [comment]
atividade finalizada dia 15/08
